export interface CustomerEntity {
    customerId: number,
      customerNoNAV: string,
      customerName: string ,
      address: string,
      district: string,
      subdistrict: string,
      province: string,
      postcode: string,
      saleZone: string,
      statusCusPrice: string,
      updateDate: string
    // customerId: number,
    // companyId: number,
    // customerNoNav: string,
    // customerName: string,
    // address: string,
    // district: string,
    // subdistrict: string,
    // province: string,
    // postcode: string,
    // phone: string,
    // vatId: string,
    // saleZone: string,
    // termPayment: string,
    // creditLimit: string,
    // isActive: boolean,
    // customerType: string,
    // updateDate: string,
    // createDate: string,
    // salePerson: string,
    // shopIdIMC: string,
}